---
abstract: "Larry Wall's Slideshow Software"
author:
  - 'Larry Wall via Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Stump
name: Stump
no_index:
  directory:
    - inc
    - share
    - t
requires:
  App::Cmd: 0.312
  File::Share: 0.01
  IO::All: 0.43
  Mouse: 0.93
  MouseX::App::Cmd: 0.08
  YAML::XS: 0.35
  perl: 5.10.0
resources:
  homepage: http://github.com/ingydotnet/stump-pm/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/ingydotnet/stump-pm.git
version: 0.06
