---
abstract: "Larry Wall's Slideshow Software"
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Stump
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  App::Cmd: '0.312'
  File::Share: '0.01'
  IO::All: '0.43'
  Mouse: '0.93'
  MouseX::App::Cmd: '0.08'
  YAML::XS: '0.35'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/stump-pm/issues
  homepage: https://github.com/ingydotnet/stump-pm
  repository: https://github.com/ingydotnet/stump-pm.git
version: '0.10'
